var hierarchy =
[
    [ "EasyKiConverter::BoundedThreadSafeQueue< T >", "classEasyKiConverter_1_1BoundedThreadSafeQueue.html", null ],
    [ "EasyKiConverter::ComponentData", "classEasyKiConverter_1_1ComponentData.html", null ],
    [ "EasyKiConverter::ComponentExportStatus", "structEasyKiConverter_1_1ComponentExportStatus.html", null ],
    [ "EasyKiConverter::EasyedaFootprintImporter", "classEasyKiConverter_1_1EasyedaFootprintImporter.html", null ],
    [ "EasyKiConverter::EasyedaSymbolImporter", "classEasyKiConverter_1_1EasyedaSymbolImporter.html", null ],
    [ "EasyKiConverter::EasyedaUtils", "classEasyKiConverter_1_1EasyedaUtils.html", null ],
    [ "EasyKiConverter::ExportService::ExportData", "structEasyKiConverter_1_1ExportService_1_1ExportData.html", null ],
    [ "EasyKiConverter::ExportOptions", "structEasyKiConverter_1_1ExportOptions.html", null ],
    [ "EasyKiConverter::ExportStatistics", "structEasyKiConverter_1_1ExportStatistics.html", null ],
    [ "EasyKiConverter::ComponentService::FetchingComponent", "structEasyKiConverter_1_1ComponentService_1_1FetchingComponent.html", null ],
    [ "EasyKiConverter::FootprintArc", "structEasyKiConverter_1_1FootprintArc.html", null ],
    [ "EasyKiConverter::FootprintBBox", "structEasyKiConverter_1_1FootprintBBox.html", null ],
    [ "EasyKiConverter::FootprintCircle", "structEasyKiConverter_1_1FootprintCircle.html", null ],
    [ "EasyKiConverter::FootprintData", "classEasyKiConverter_1_1FootprintData.html", null ],
    [ "EasyKiConverter::FootprintDataSerializer", "classEasyKiConverter_1_1FootprintDataSerializer.html", null ],
    [ "EasyKiConverter::FootprintGraphicsGenerator", "classEasyKiConverter_1_1FootprintGraphicsGenerator.html", null ],
    [ "EasyKiConverter::FootprintHole", "structEasyKiConverter_1_1FootprintHole.html", null ],
    [ "EasyKiConverter::FootprintInfo", "structEasyKiConverter_1_1FootprintInfo.html", null ],
    [ "EasyKiConverter::FootprintOutline", "structEasyKiConverter_1_1FootprintOutline.html", null ],
    [ "EasyKiConverter::FootprintPad", "structEasyKiConverter_1_1FootprintPad.html", null ],
    [ "EasyKiConverter::FootprintRectangle", "structEasyKiConverter_1_1FootprintRectangle.html", null ],
    [ "EasyKiConverter::FootprintSolidRegion", "structEasyKiConverter_1_1FootprintSolidRegion.html", null ],
    [ "EasyKiConverter::FootprintText", "structEasyKiConverter_1_1FootprintText.html", null ],
    [ "EasyKiConverter::FootprintTrack", "structEasyKiConverter_1_1FootprintTrack.html", null ],
    [ "EasyKiConverter::GeometryUtils", "classEasyKiConverter_1_1GeometryUtils.html", null ],
    [ "EasyKiConverter::IAppender", "classEasyKiConverter_1_1IAppender.html", [
      [ "EasyKiConverter::ConsoleAppender", "classEasyKiConverter_1_1ConsoleAppender.html", null ],
      [ "EasyKiConverter::FileAppender", "classEasyKiConverter_1_1FileAppender.html", null ]
    ] ],
    [ "EasyKiConverter::IFormatter", "classEasyKiConverter_1_1IFormatter.html", [
      [ "EasyKiConverter::PatternFormatter", "classEasyKiConverter_1_1PatternFormatter.html", null ]
    ] ],
    [ "EasyKiConverter::LayerDefinition", "structEasyKiConverter_1_1LayerDefinition.html", null ],
    [ "EasyKiConverter::LayerMapper", "classEasyKiConverter_1_1LayerMapper.html", null ],
    [ "EasyKiConverter::LogRecord", "structEasyKiConverter_1_1LogRecord.html", null ],
    [ "EasyKiConverter::LogUtils", "classEasyKiConverter_1_1LogUtils.html", null ],
    [ "EasyKiConverter::MemorySnapshot", "structEasyKiConverter_1_1MemorySnapshot.html", null ],
    [ "EasyKiConverter::Model3DBase", "structEasyKiConverter_1_1Model3DBase.html", null ],
    [ "EasyKiConverter::Model3DData", "classEasyKiConverter_1_1Model3DData.html", null ],
    [ "EasyKiConverter::ComponentExportStatus::NetworkDiagnostics", "structEasyKiConverter_1_1ComponentExportStatus_1_1NetworkDiagnostics.html", null ],
    [ "EasyKiConverter::ObjectVisibility", "structEasyKiConverter_1_1ObjectVisibility.html", null ],
    [ "EasyKiConverter::PathSecurity", "classEasyKiConverter_1_1PathSecurity.html", null ],
    [ "EasyKiConverter::PipelineCleanup", "classEasyKiConverter_1_1PipelineCleanup.html", null ],
    [ "EasyKiConverter::PipelineProgress", "structEasyKiConverter_1_1PipelineProgress.html", null ],
    [ "EasyKiConverter::PipelineQueueManager", "classEasyKiConverter_1_1PipelineQueueManager.html", null ],
    [ "EasyKiConverter::PipelineStatistics", "classEasyKiConverter_1_1PipelineStatistics.html", null ],
    [ "QAbstractListModel", null, [
      [ "EasyKiConverter::ComponentListViewModel", "classEasyKiConverter_1_1ComponentListViewModel.html", null ]
    ] ],
    [ "QObject", null, [
      [ "EasyKiConverter::BomParser", "classEasyKiConverter_1_1BomParser.html", null ],
      [ "EasyKiConverter::ComponentDataCollector", "classEasyKiConverter_1_1ComponentDataCollector.html", null ],
      [ "EasyKiConverter::ComponentExportTask", "classEasyKiConverter_1_1ComponentExportTask.html", null ],
      [ "EasyKiConverter::ComponentListItemData", "classEasyKiConverter_1_1ComponentListItemData.html", null ],
      [ "EasyKiConverter::ComponentService", "classEasyKiConverter_1_1ComponentService.html", null ],
      [ "EasyKiConverter::ConfigManager", "classEasyKiConverter_1_1ConfigManager.html", null ],
      [ "EasyKiConverter::ConfigService", "classEasyKiConverter_1_1ConfigService.html", null ],
      [ "EasyKiConverter::EasyedaApi", "classEasyKiConverter_1_1EasyedaApi.html", null ],
      [ "EasyKiConverter::EasyedaImporter", "classEasyKiConverter_1_1EasyedaImporter.html", null ],
      [ "EasyKiConverter::ExportProgressViewModel", "classEasyKiConverter_1_1ExportProgressViewModel.html", null ],
      [ "EasyKiConverter::ExportService", "classEasyKiConverter_1_1ExportService.html", [
        [ "EasyKiConverter::ExportServicePipeline", "classEasyKiConverter_1_1ExportServicePipeline.html", null ]
      ] ],
      [ "EasyKiConverter::ExportSettingsViewModel", "classEasyKiConverter_1_1ExportSettingsViewModel.html", null ],
      [ "EasyKiConverter::ExportWorker", "classEasyKiConverter_1_1ExportWorker.html", null ],
      [ "EasyKiConverter::Exporter3DModel", "classEasyKiConverter_1_1Exporter3DModel.html", null ],
      [ "EasyKiConverter::ExporterFootprint", "classEasyKiConverter_1_1ExporterFootprint.html", null ],
      [ "EasyKiConverter::ExporterSymbol", "classEasyKiConverter_1_1ExporterSymbol.html", null ],
      [ "EasyKiConverter::FetchWorker", "classEasyKiConverter_1_1FetchWorker.html", null ],
      [ "EasyKiConverter::INetworkAdapter", "classEasyKiConverter_1_1INetworkAdapter.html", [
        [ "EasyKiConverter::NetworkUtils", "classEasyKiConverter_1_1NetworkUtils.html", null ]
      ] ],
      [ "EasyKiConverter::JLCDatasheet", "classEasyKiConverter_1_1JLCDatasheet.html", null ],
      [ "EasyKiConverter::LanguageManager", "classEasyKiConverter_1_1LanguageManager.html", null ],
      [ "EasyKiConverter::LcscImageService", "classEasyKiConverter_1_1LcscImageService.html", null ],
      [ "EasyKiConverter::Logger", "classEasyKiConverter_1_1Logger.html", null ],
      [ "EasyKiConverter::NetworkWorker", "classEasyKiConverter_1_1NetworkWorker.html", null ],
      [ "EasyKiConverter::ProcessWorker", "classEasyKiConverter_1_1ProcessWorker.html", null ],
      [ "EasyKiConverter::StageHandler", "classEasyKiConverter_1_1StageHandler.html", [
        [ "EasyKiConverter::FetchStageHandler", "classEasyKiConverter_1_1FetchStageHandler.html", null ],
        [ "EasyKiConverter::ProcessStageHandler", "classEasyKiConverter_1_1ProcessStageHandler.html", null ],
        [ "EasyKiConverter::WriteStageHandler", "classEasyKiConverter_1_1WriteStageHandler.html", null ]
      ] ],
      [ "EasyKiConverter::ThemeSettingsViewModel", "classEasyKiConverter_1_1ThemeSettingsViewModel.html", null ],
      [ "EasyKiConverter::WriteWorker", "classEasyKiConverter_1_1WriteWorker.html", null ]
    ] ],
    [ "QRunnable", null, [
      [ "EasyKiConverter::ComponentExportTask", "classEasyKiConverter_1_1ComponentExportTask.html", null ],
      [ "EasyKiConverter::ExportWorker", "classEasyKiConverter_1_1ExportWorker.html", null ],
      [ "EasyKiConverter::FetchWorker", "classEasyKiConverter_1_1FetchWorker.html", null ],
      [ "EasyKiConverter::NetworkWorker", "classEasyKiConverter_1_1NetworkWorker.html", null ],
      [ "EasyKiConverter::ProcessWorker", "classEasyKiConverter_1_1ProcessWorker.html", null ],
      [ "EasyKiConverter::WriteWorker", "classEasyKiConverter_1_1WriteWorker.html", null ]
    ] ],
    [ "EasyKiConverter::QtLogAdapter", "classEasyKiConverter_1_1QtLogAdapter.html", null ],
    [ "EasyKiConverter::ScopedDataClearer", "classEasyKiConverter_1_1ScopedDataClearer.html", null ],
    [ "EasyKiConverter::ScopedTracer", "classEasyKiConverter_1_1ScopedTracer.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgArcEndpoints", "structEasyKiConverter_1_1GeometryUtils_1_1SvgArcEndpoints.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgArcResult", "structEasyKiConverter_1_1GeometryUtils_1_1SvgArcResult.html", null ],
    [ "EasyKiConverter::SvgPathParser", "classEasyKiConverter_1_1SvgPathParser.html", null ],
    [ "EasyKiConverter::GeometryUtils::SvgPoint", "structEasyKiConverter_1_1GeometryUtils_1_1SvgPoint.html", null ],
    [ "EasyKiConverter::SymbolArc", "structEasyKiConverter_1_1SymbolArc.html", null ],
    [ "EasyKiConverter::SymbolBBox", "structEasyKiConverter_1_1SymbolBBox.html", null ],
    [ "EasyKiConverter::SymbolCircle", "structEasyKiConverter_1_1SymbolCircle.html", null ],
    [ "EasyKiConverter::SymbolData", "classEasyKiConverter_1_1SymbolData.html", null ],
    [ "EasyKiConverter::SymbolDataSerializer", "classEasyKiConverter_1_1SymbolDataSerializer.html", null ],
    [ "EasyKiConverter::SymbolEllipse", "structEasyKiConverter_1_1SymbolEllipse.html", null ],
    [ "EasyKiConverter::SymbolGraphicsGenerator", "classEasyKiConverter_1_1SymbolGraphicsGenerator.html", null ],
    [ "EasyKiConverter::SymbolInfo", "structEasyKiConverter_1_1SymbolInfo.html", null ],
    [ "EasyKiConverter::SymbolPart", "structEasyKiConverter_1_1SymbolPart.html", null ],
    [ "EasyKiConverter::SymbolPath", "structEasyKiConverter_1_1SymbolPath.html", null ],
    [ "EasyKiConverter::SymbolPin", "structEasyKiConverter_1_1SymbolPin.html", null ],
    [ "EasyKiConverter::SymbolPinClock", "structEasyKiConverter_1_1SymbolPinClock.html", null ],
    [ "EasyKiConverter::SymbolPinDot", "structEasyKiConverter_1_1SymbolPinDot.html", null ],
    [ "EasyKiConverter::SymbolPinDotBis", "structEasyKiConverter_1_1SymbolPinDotBis.html", null ],
    [ "EasyKiConverter::SymbolPinName", "structEasyKiConverter_1_1SymbolPinName.html", null ],
    [ "EasyKiConverter::SymbolPinPath", "structEasyKiConverter_1_1SymbolPinPath.html", null ],
    [ "EasyKiConverter::SymbolPinSettings", "structEasyKiConverter_1_1SymbolPinSettings.html", null ],
    [ "EasyKiConverter::SymbolPolygon", "structEasyKiConverter_1_1SymbolPolygon.html", null ],
    [ "EasyKiConverter::SymbolPolyline", "structEasyKiConverter_1_1SymbolPolyline.html", null ],
    [ "EasyKiConverter::SymbolRectangle", "structEasyKiConverter_1_1SymbolRectangle.html", null ],
    [ "EasyKiConverter::SymbolText", "structEasyKiConverter_1_1SymbolText.html", null ],
    [ "EasyKiConverter::ThumbnailGenerator", "classEasyKiConverter_1_1ThumbnailGenerator.html", null ],
    [ "EasyKiConverter::TimeLogger", "classEasyKiConverter_1_1TimeLogger.html", null ]
];